/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CursosController;
import entity.Curso;
import static java.awt.SystemColor.window;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.WindowListener;
import viewmodel.CursosViewModel;

/**
 *
 * @author jonathan
 */
public class CursosView extends javax.swing.JFrame implements java.util.Observer {

      private  CursosViewModel model;
      private  CursosController controller;
    
    
    /**
     * Creates new form CursosView
     */
    public CursosView(CursosViewModel model, CursosController controller) {
        this.setModel(model);
        this.setController(controller);
        initComponents();
    }
    
    public CursosView() {
        
        initComponents();
    }

    public CursosViewModel getModel() {
        return model;
    }

    public void setModel(CursosViewModel model) {
        this.model = model;
          model.addObserver(this);
    }

    public CursosController getController() {
        return controller;
    }

    public void setController(CursosController controller) {
        this.controller = controller;
    }
    
    
    private   void updateComboBoxes(){
      
  //this.controller.setComboBox();
  //System.out.println("ADIOS");
  //System.out.println(this.controller.getModel().getCiclos());
  //if(this.controller.getModel().getCursos()!= null)
    this.cursosComboBox.setModel(this.controller.getModel().getCursos());
  
  }
    
        @Override
    public void update(java.util.Observable updatedModel,Object parametros){
          System.out.println("ADIOS");
       this.updateComboBoxes();
    }
   
   
   class CustomComponentListener implements ComponentListener {
       
       private final CursosView  view;
       
       public CustomComponentListener(CursosView view){
           this.view=view;
       }

       @Override
      public void componentResized(ComponentEvent e) {

      }

       @Override
      public void componentMoved(ComponentEvent e) {

      }

       @Override
      public void componentShown(ComponentEvent e) {
       this.view.getController().setComboBox();
      }

       @Override
      public void componentHidden(ComponentEvent e) {

      }
   }

    @Override
    public synchronized void addComponentListener(ComponentListener cl) {
       
       cl=new CustomComponentListener(this);

        super.addComponentListener(cl); //To change body of generated methods, choose Tools | Templates.
    }

    private Curso toCurso(){
        return (Curso)this.cursosComboBox.getSelectedItem();
    }
    
//   .addComponentListener(new ComponentAdapter() {
//   public void componentHidden(ComponentEvent e) {
//      /* code run when component hidden*/
//   }
//   public void componentShown(ComponentEvent e) {
//      /* code run when component shown */
//   }
//});

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cursosComboBox = new javax.swing.JComboBox<>();
        verButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione un Curso");

        cursosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        verButton.setText("Ver Grupos");
        verButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 3, 10)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(cursosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(verButton))
                    .addComponent(jButton1))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(verButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verButtonActionPerformed
       this.controller.goToGrupos(this.toCurso());
    }//GEN-LAST:event_verButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.controller.goBack(this.getLocation());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cursosComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton verButton;
    // End of variables declaration//GEN-END:variables
}





