/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GruposController;
import entity.Grupo;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import viewmodel.GruposViewModel;

/**
 *
 * @author jonathan
 */
public class GruposView extends javax.swing.JFrame implements java.util.Observer {

    /**
     * Creates new form GruposView
     */
    
    private GruposController controller;
    private GruposViewModel model;
    
    public GruposView() {
        initComponents();
    }

    public GruposController getController() {
        return controller;
    }

    public void setController(GruposController controller) {
        this.controller = controller;
    }

    public GruposViewModel getModel() {
        return model;
    }

    public void setModel(GruposViewModel model) {
        this.model = model;
        this.model.addObserver(this);
    }

        private   void updateComboBoxes(){
      
  //this.controller.setComboBox();
  //System.out.println("ADIOS");
  //System.out.println(this.controller.getModel().getCiclos());
  //if(this.controller.getModel().getCursos()!= null)
    this.gruposComboBox.setModel(this.controller.getModel().getGrupos());
  
  }
    @Override
    public void update(java.util.Observable updatedModel,Object parametros){
       this.updateComboBoxes();
    }
        @Override
    public synchronized void addComponentListener(ComponentListener cl) {
        System.out.println("HOOOOLAAAAAA AC");
       cl=new GruposComponentListener(this);
       
        super.addComponentListener(cl); //To change body of generated methods, choose Tools | Templates.
    }

        private Grupo toGrupo(){
            return (Grupo)this.gruposComboBox.getSelectedItem();
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        gruposComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("     Seleccione un grupo");

        gruposComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Ver Estudiantes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("DejaVu Sans", 3, 9)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gruposComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(gruposComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.controller.goToNotas(this.toGrupo());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.controller.goBack(this.getLocation());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> gruposComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
 class GruposComponentListener implements ComponentListener {
       
       private final GruposView  view;
       
       public GruposComponentListener(GruposView view){
           this.view=view;
       }

       @Override
      public void componentResized(ComponentEvent e) {

      }

       @Override
      public void componentMoved(ComponentEvent e) {

      }

       @Override
      public void componentShown(ComponentEvent e) {
          
           System.out.println("HOOOOLAAAAAA GCS");
       this.view.getController().setComboBox();
       //this.view.se
      }

       @Override
      public void componentHidden(ComponentEvent e) {

      }
   }